services:
  - type: web
    name: discord-bot-bag-v2
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node index.render.js
    healthCheckPath: /health
    repo: https://github.com/your-username/discord-bot-bag-v2.git
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID  
        sync: false
      - key: DATABASE_URL
        sync: false
    disk:
      name: data-disk
      mountPath: /opt/render/project/src/data
      sizeGB: 1